#!/bin/bash

# Inspired by various Google searches, but also by the book "tmux: productive
# Mouse-Free Devleopment".


session="tsomkes"

# Create session if it doesn't already exist
tmux has-session -t "$session"
if [ $? != 0 ]
then
    window="main"

    tmux new-session -s "$session" -n "$window" -d
    tmux split-window -t "$session"
    tmux split-window -t "$session"

    tmux select-layout -t "$session":"$window" main-vertical

    tmux resize-pane -t "$session":"$window".0 -x 50

    # Focus on main pane
    tmux select-pane -t "$session".0
fi

tmux attach -t "$session"
