#! /usr/bin/python3

import argparse
from datetime import date
from os import listdir, path
import re


PATH = path.expanduser('~/Dropbox/zdo')
PATH_PROJECTS = PATH + '/projects'


def CreateProject(name):
    '''Create file under projects/, if not already present'''
    filename = name.lower().replace(' ', '_') + '.txt'
    filepath = path.join(PATH_PROJECTS, filename)
    if not path.isfile(filepath):
        addedDateStr = "\tAdded " + str(date.today())
        with open(filepath, 'w') as f:
            f.write(name + '\n')
            f.write('=' * len(name) + '\n\n')
            f.write(addedDateStr)


def GetProjectFiles():
    files = [path.join(PATH_PROJECTS, f) for f in listdir(PATH_PROJECTS) if
             path.isfile(path.join(PATH_PROJECTS, f))]
    return files


def GetActiveProjectFiles():
    files = ["misc.txt"]
    files.extend(GetProjectFiles())
    return files


def FindLines(filename, firstCharacter):
    title = ""
    lines = ""

    with open(filename) as f:
        title = f.readline()

        for line in f:
            r = re.search('^' + firstCharacter, line)
            if r:
                lines += line

    if lines != "":
        return title + lines


def ListNextActionsBrief(filename):
    results = FindLines(filename, '>')

    if results != "":
        print(results)


def ListWaitingForBrief(filename):
    results = FindLines(filename, '<')

    if results:
        print(results)


def ListProjects():
    projectFiles = sorted(GetActiveProjectFiles())

    for pf in projectFiles:
        with open(pf) as f:
            title = f.readline().strip()
            if title != 'Misc':
                print(title)


parser = argparse.ArgumentParser()
parser.add_argument('action', choices=['na', 'wf', 'pa', 'lp'])
parser.add_argument('title', nargs="*")
args = parser.parse_args()

if args.action == 'na':
    for f in GetActiveProjectFiles():
        ListNextActionsBrief(f)

elif args.action == 'wf':
    for f in GetActiveProjectFiles():
        ListWaitingForBrief(f)

elif args.action == 'pa':
    title = ' '.join(args.title)
    CreateProject(title)

elif args.action == 'lp':
    ListProjects()
