#!/bin/bash

# Partly inspired by https://davidtranscend.com/blog/check-tmux-session-exists-script/


project=$1

# Create session if it doesn't already exist
tmux has-session -t $project 2>/dev/null
if [ $? != 0 ]
then
    scriptPath=$(dirname "$0")/tmuxz-projects/$project.sh
    #eval "$scriptPath"
    $scriptPath
fi

tmux attach-session -t "$session"
